insert into Tournaments (name, year, location, winner_id) values ('Grand Prix', 1998, 'Australia', 900);
insert into Tournaments (name, year, location, winner_id) values ('Masters Open', 2003, 'São Paulo', 78);
insert into Tournaments (name, year, location, winner_id) values ('Masters Open', 2018, 'UK', 444);
insert into Tournaments (name, year, location, winner_id) values ('World Series', 1988, 'Tokyo', 458);
insert into Tournaments (name, year, location, winner_id) values ('Spring Invitational', 2020, 'Brazil', 907);
insert into Tournaments (name, year, location, winner_id) values ('World Series', 2003, 'Canada', 244);
insert into Tournaments (name, year, location, winner_id) values ('World Series', 2006, 'Australia', 618);
insert into Tournaments (name, year, location, winner_id) values ('Winter Classic', 2008, 'Sydney', 622);
insert into Tournaments (name, year, location, winner_id) values ('World Series', 2002, 'Japan', 930);
insert into Tournaments (name, year, location, winner_id) values ('Continental Championship', 2024, 'Germany', 403);
insert into Tournaments (name, year, location, winner_id) values ('Winter Classic', 2021, 'Sydney', 263);
insert into Tournaments (name, year, location, winner_id) values ('Grand Prix', 1994, 'London', 926);
insert into Tournaments (name, year, location, winner_id) values ('Spring Invitational', 1991, 'Canada', 434);
insert into Tournaments (name, year, location, winner_id) values ('Continental Championship', 1992, 'New York', 388);
insert into Tournaments (name, year, location, winner_id) values ('Champions Cup', 1988, 'New York', 915);
insert into Tournaments (name, year, location, winner_id) values ('Spring Invitational', 2016, 'Sydney', 874);
insert into Tournaments (name, year, location, winner_id) values ('World Series', 1991, 'Canada', 693);
insert into Tournaments (name, year, location, winner_id) values ('Continental Championship', 1989, 'Japan', 763);
insert into Tournaments (name, year, location, winner_id) values ('Grand Prix', 2002, 'London', 690);
insert into Tournaments (name, year, location, winner_id) values ('Grand Prix', 2020, 'London', 306);
insert into Tournaments (name, year, location, winner_id) values ('Masters Open', 2018, 'Canada', 208);
insert into Tournaments (name, year, location, winner_id) values ('Masters Open', 1983, 'São Paulo', 987);
insert into Tournaments (name, year, location, winner_id) values ('World Series', 2025, 'Toronto', 478);
insert into Tournaments (name, year, location, winner_id) values ('Grand Prix', 1989, 'Berlin', 185);
insert into Tournaments (name, year, location, winner_id) values ('Champions Cup', 1992, 'Toronto', 95);
insert into Tournaments (name, year, location, winner_id) values ('Spring Invitational', 1994, 'UK', 953);
insert into Tournaments (name, year, location, winner_id) values ('Grand Prix', 2007, 'Australia', 27);
insert into Tournaments (name, year, location, winner_id) values ('Masters Open', 2005, 'Australia', 842);
insert into Tournaments (name, year, location, winner_id) values ('Continental Championship', 2012, 'UK', 965);
insert into Tournaments (name, year, location, winner_id) values ('Continental Championship', 2016, 'São Paulo', 927);
insert into Tournaments (name, year, location, winner_id) values ('Spring Invitational', 1988, 'Sydney', 949);
insert into Tournaments (name, year, location, winner_id) values ('Champions Cup', 1981, 'USA', 669);
insert into Tournaments (name, year, location, winner_id) values ('World Series', 2018, 'Tokyo', 815);
insert into Tournaments (name, year, location, winner_id) values ('Champions Cup', 1997, 'Brazil', 747);
insert into Tournaments (name, year, location, winner_id) values ('World Series', 2024, 'Canada', 791);
insert into Tournaments (name, year, location, winner_id) values ('Grand Prix', 1987, 'Australia', 554);
insert into Tournaments (name, year, location, winner_id) values ('Grand Prix', 1999, 'Berlin', 743);
insert into Tournaments (name, year, location, winner_id) values ('World Series', 1999, 'UK', 389);
insert into Tournaments (name, year, location, winner_id) values ('Spring Invitational', 2005, 'UK', 829);
insert into Tournaments (name, year, location, winner_id) values ('Grand Prix', 2022, 'Sydney', 289);
insert into Tournaments (name, year, location, winner_id) values ('Grand Prix', 1983, 'Japan', 143);
insert into Tournaments (name, year, location, winner_id) values ('Continental Championship', 1987, 'Toronto', 533);
insert into Tournaments (name, year, location, winner_id) values ('Masters Open', 2000, 'Toronto', 230);
insert into Tournaments (name, year, location, winner_id) values ('Continental Championship', 1993, 'Germany', 951);
insert into Tournaments (name, year, location, winner_id) values ('Winter Classic', 2012, 'Japan', 7);
insert into Tournaments (name, year, location, winner_id) values ('Continental Championship', 2008, 'Japan', 68);
insert into Tournaments (name, year, location, winner_id) values ('Masters Open', 1992, 'Australia', 798);
insert into Tournaments (name, year, location, winner_id) values ('Spring Invitational', 2002, 'London', 230);
insert into Tournaments (name, year, location, winner_id) values ('Masters Open', 1992, 'Tokyo', 886);
insert into Tournaments (name, year, location, winner_id) values ('Spring Invitational', 1995, 'Berlin', 263);
insert into Tournaments (name, year, location, winner_id) values ('Champions Cup', 2006, 'UK', 802);
insert into Tournaments (name, year, location, winner_id) values ('Continental Championship', 2016, 'Canada', 138);
insert into Tournaments (name, year, location, winner_id) values ('Masters Open', 1996, 'New York', 88);
insert into Tournaments (name, year, location, winner_id) values ('Spring Invitational', 1987, 'London', 631);
insert into Tournaments (name, year, location, winner_id) values ('Masters Open', 2002, 'Australia', 599);
insert into Tournaments (name, year, location, winner_id) values ('Champions Cup', 2023, 'São Paulo', 58);
insert into Tournaments (name, year, location, winner_id) values ('World Series', 2011, 'Berlin', 162);
insert into Tournaments (name, year, location, winner_id) values ('Masters Open', 1988, 'Brazil', 240);
insert into Tournaments (name, year, location, winner_id) values ('Grand Prix', 2016, 'Japan', 482);
insert into Tournaments (name, year, location, winner_id) values ('Grand Prix', 2008, 'São Paulo', 15);
insert into Tournaments (name, year, location, winner_id) values ('Spring Invitational', 1988, 'Toronto', 482);
insert into Tournaments (name, year, location, winner_id) values ('Continental Championship', 2013, 'Sydney', 177);
insert into Tournaments (name, year, location, winner_id) values ('Spring Invitational', 2013, 'New York', 745);
insert into Tournaments (name, year, location, winner_id) values ('Continental Championship', 2000, 'UK', 742);
insert into Tournaments (name, year, location, winner_id) values ('Winter Classic', 2008, 'Australia', 979);
insert into Tournaments (name, year, location, winner_id) values ('World Series', 1983, 'Australia', 292);
insert into Tournaments (name, year, location, winner_id) values ('Spring Invitational', 1986, 'Tokyo', 956);
insert into Tournaments (name, year, location, winner_id) values ('Masters Open', 1989, 'Germany', 61);
insert into Tournaments (name, year, location, winner_id) values ('Champions Cup', 2025, 'Tokyo', 860);
insert into Tournaments (name, year, location, winner_id) values ('Grand Prix', 2009, 'Sydney', 690);
insert into Tournaments (name, year, location, winner_id) values ('World Series', 2020, 'London', 74);
insert into Tournaments (name, year, location, winner_id) values ('Champions Cup', 1998, 'UK', 964);
insert into Tournaments (name, year, location, winner_id) values ('Spring Invitational', 2024, 'Canada', 623);
insert into Tournaments (name, year, location, winner_id) values ('Champions Cup', 1999, 'Japan', 9);
insert into Tournaments (name, year, location, winner_id) values ('Spring Invitational', 1986, 'Tokyo', 55);
insert into Tournaments (name, year, location, winner_id) values ('Winter Classic', 1997, 'USA', 66);
insert into Tournaments (name, year, location, winner_id) values ('Continental Championship', 1999, 'Australia', 662);
insert into Tournaments (name, year, location, winner_id) values ('World Series', 2016, 'UK', 589);
insert into Tournaments (name, year, location, winner_id) values ('Continental Championship', 1982, 'Germany', 422);
insert into Tournaments (name, year, location, winner_id) values ('Champions Cup', 1998, 'London', 119);
insert into Tournaments (name, year, location, winner_id) values ('Winter Classic', 1992, 'Japan', 118);
insert into Tournaments (name, year, location, winner_id) values ('Masters Open', 2016, 'Australia', 58);
insert into Tournaments (name, year, location, winner_id) values ('Grand Prix', 1985, 'Brazil', 436);
insert into Tournaments (name, year, location, winner_id) values ('Continental Championship', 2000, 'London', 504);
insert into Tournaments (name, year, location, winner_id) values ('Masters Open', 1998, 'Tokyo', 978);
insert into Tournaments (name, year, location, winner_id) values ('Masters Open', 1996, 'Sydney', 854);
insert into Tournaments (name, year, location, winner_id) values ('Spring Invitational', 2005, 'Sydney', 254);
insert into Tournaments (name, year, location, winner_id) values ('Spring Invitational', 2006, 'Germany', 103);
insert into Tournaments (name, year, location, winner_id) values ('Masters Open', 1990, 'USA', 273);
insert into Tournaments (name, year, location, winner_id) values ('Grand Prix', 2023, 'UK', 816);
insert into Tournaments (name, year, location, winner_id) values ('Grand Prix', 2022, 'Toronto', 79);
insert into Tournaments (name, year, location, winner_id) values ('Grand Prix', 1984, 'Sydney', 677);
insert into Tournaments (name, year, location, winner_id) values ('Spring Invitational', 1980, 'Toronto', 155);
insert into Tournaments (name, year, location, winner_id) values ('Continental Championship', 1995, 'Toronto', 54);
insert into Tournaments (name, year, location, winner_id) values ('Champions Cup', 1995, 'Berlin', 601);
insert into Tournaments (name, year, location, winner_id) values ('Masters Open', 1999, 'Berlin', 654);
insert into Tournaments (name, year, location, winner_id) values ('Continental Championship', 2016, 'São Paulo', 406);
insert into Tournaments (name, year, location, winner_id) values ('Grand Prix', 2004, 'São Paulo', 504);
insert into Tournaments (name, year, location, winner_id) values ('Masters Open', 2020, 'Germany', 387);
insert into Tournaments (name, year, location, winner_id) values ('Continental Championship', 2008, 'London', 30);
insert into Tournaments (name, year, location, winner_id) values ('Continental Championship', 2025, 'Germany', 518);
insert into Tournaments (name, year, location, winner_id) values ('Winter Classic', 1981, 'Sydney', 678);
insert into Tournaments (name, year, location, winner_id) values ('Spring Invitational', 2000, 'Canada', 269);
insert into Tournaments (name, year, location, winner_id) values ('Winter Classic', 2006, 'New York', 786);
insert into Tournaments (name, year, location, winner_id) values ('Spring Invitational', 1980, 'London', 183);
insert into Tournaments (name, year, location, winner_id) values ('Champions Cup', 2016, 'Japan', 907);
insert into Tournaments (name, year, location, winner_id) values ('Continental Championship', 1996, 'London', 698);
insert into Tournaments (name, year, location, winner_id) values ('Champions Cup', 1991, 'Japan', 340);
insert into Tournaments (name, year, location, winner_id) values ('World Series', 2006, 'USA', 64);
insert into Tournaments (name, year, location, winner_id) values ('Winter Classic', 1993, 'Tokyo', 473);
insert into Tournaments (name, year, location, winner_id) values ('Champions Cup', 2019, 'USA', 943);
insert into Tournaments (name, year, location, winner_id) values ('Spring Invitational', 1983, 'London', 391);
insert into Tournaments (name, year, location, winner_id) values ('Spring Invitational', 1983, 'São Paulo', 257);
insert into Tournaments (name, year, location, winner_id) values ('World Series', 1998, 'USA', 661);
insert into Tournaments (name, year, location, winner_id) values ('Winter Classic', 1983, 'Germany', 117);
insert into Tournaments (name, year, location, winner_id) values ('Masters Open', 1995, 'Canada', 38);
insert into Tournaments (name, year, location, winner_id) values ('Spring Invitational', 1995, 'Japan', 477);
insert into Tournaments (name, year, location, winner_id) values ('Spring Invitational', 1989, 'Canada', 685);
insert into Tournaments (name, year, location, winner_id) values ('Spring Invitational', 2025, 'New York', 45);
insert into Tournaments (name, year, location, winner_id) values ('Continental Championship', 2024, 'Berlin', 843);
insert into Tournaments (name, year, location, winner_id) values ('Spring Invitational', 2022, 'Brazil', 226);
insert into Tournaments (name, year, location, winner_id) values ('Grand Prix', 2002, 'Canada', 221);
insert into Tournaments (name, year, location, winner_id) values ('Spring Invitational', 2008, 'Tokyo', 865);
insert into Tournaments (name, year, location, winner_id) values ('Champions Cup', 1984, 'London', 844);
insert into Tournaments (name, year, location, winner_id) values ('Continental Championship', 2001, 'Brazil', 907);
insert into Tournaments (name, year, location, winner_id) values ('World Series', 2020, 'London', 802);
insert into Tournaments (name, year, location, winner_id) values ('World Series', 2015, 'Tokyo', 524);
insert into Tournaments (name, year, location, winner_id) values ('World Series', 2009, 'USA', 220);
insert into Tournaments (name, year, location, winner_id) values ('Spring Invitational', 1988, 'USA', 228);
insert into Tournaments (name, year, location, winner_id) values ('Champions Cup', 2010, 'Berlin', 265);
insert into Tournaments (name, year, location, winner_id) values ('Champions Cup', 2012, 'New York', 95);
insert into Tournaments (name, year, location, winner_id) values ('Spring Invitational', 2019, 'USA', 981);
insert into Tournaments (name, year, location, winner_id) values ('Winter Classic', 2018, 'Japan', 262);
insert into Tournaments (name, year, location, winner_id) values ('World Series', 2011, 'Tokyo', 193);
insert into Tournaments (name, year, location, winner_id) values ('World Series', 2005, 'Germany', 356);
insert into Tournaments (name, year, location, winner_id) values ('Spring Invitational', 1988, 'New York', 351);
insert into Tournaments (name, year, location, winner_id) values ('Masters Open', 1989, 'Toronto', 86);
insert into Tournaments (name, year, location, winner_id) values ('Champions Cup', 2016, 'New York', 21);
insert into Tournaments (name, year, location, winner_id) values ('Winter Classic', 2014, 'Berlin', 141);
insert into Tournaments (name, year, location, winner_id) values ('Champions Cup', 2005, 'New York', 255);
insert into Tournaments (name, year, location, winner_id) values ('Continental Championship', 2014, 'Berlin', 834);
insert into Tournaments (name, year, location, winner_id) values ('Winter Classic', 1992, 'Berlin', 212);
insert into Tournaments (name, year, location, winner_id) values ('Winter Classic', 1990, 'USA', 813);
insert into Tournaments (name, year, location, winner_id) values ('Grand Prix', 2007, 'Canada', 228);
insert into Tournaments (name, year, location, winner_id) values ('Winter Classic', 2009, 'Germany', 339);
insert into Tournaments (name, year, location, winner_id) values ('Grand Prix', 1985, 'São Paulo', 956);
insert into Tournaments (name, year, location, winner_id) values ('Spring Invitational', 1990, 'USA', 333);
insert into Tournaments (name, year, location, winner_id) values ('Grand Prix', 2008, 'Tokyo', 251);
insert into Tournaments (name, year, location, winner_id) values ('Spring Invitational', 1980, 'São Paulo', 90);
insert into Tournaments (name, year, location, winner_id) values ('Continental Championship', 2022, 'Japan', 412);
insert into Tournaments (name, year, location, winner_id) values ('World Series', 2024, 'Toronto', 525);
insert into Tournaments (name, year, location, winner_id) values ('World Series', 1993, 'Berlin', 489);
insert into Tournaments (name, year, location, winner_id) values ('Continental Championship', 2013, 'London', 377);
insert into Tournaments (name, year, location, winner_id) values ('Grand Prix', 2021, 'London', 525);
insert into Tournaments (name, year, location, winner_id) values ('World Series', 1997, 'Germany', 217);
insert into Tournaments (name, year, location, winner_id) values ('Spring Invitational', 1992, 'Japan', 67);
insert into Tournaments (name, year, location, winner_id) values ('Winter Classic', 1986, 'Sydney', 574);
insert into Tournaments (name, year, location, winner_id) values ('Winter Classic', 1983, 'Japan', 476);
insert into Tournaments (name, year, location, winner_id) values ('Masters Open', 2025, 'Brazil', 817);
insert into Tournaments (name, year, location, winner_id) values ('Spring Invitational', 1995, 'London', 494);
insert into Tournaments (name, year, location, winner_id) values ('Champions Cup', 1986, 'Tokyo', 19);
insert into Tournaments (name, year, location, winner_id) values ('Champions Cup', 1989, 'Brazil', 173);
insert into Tournaments (name, year, location, winner_id) values ('Continental Championship', 2012, 'London', 736);
insert into Tournaments (name, year, location, winner_id) values ('Spring Invitational', 2007, 'Berlin', 413);
insert into Tournaments (name, year, location, winner_id) values ('Grand Prix', 1999, 'Sydney', 454);
insert into Tournaments (name, year, location, winner_id) values ('Spring Invitational', 2015, 'Tokyo', 151);
insert into Tournaments (name, year, location, winner_id) values ('World Series', 1999, 'Sydney', 902);
insert into Tournaments (name, year, location, winner_id) values ('Spring Invitational', 2011, 'New York', 622);
insert into Tournaments (name, year, location, winner_id) values ('Champions Cup', 1982, 'Japan', 189);
insert into Tournaments (name, year, location, winner_id) values ('Grand Prix', 2003, 'Toronto', 721);
insert into Tournaments (name, year, location, winner_id) values ('Continental Championship', 2001, 'Japan', 571);
insert into Tournaments (name, year, location, winner_id) values ('Continental Championship', 2019, 'Germany', 313);
insert into Tournaments (name, year, location, winner_id) values ('Continental Championship', 1994, 'London', 312);
insert into Tournaments (name, year, location, winner_id) values ('Spring Invitational', 1982, 'Germany', 907);
insert into Tournaments (name, year, location, winner_id) values ('Champions Cup', 1991, 'London', 912);
insert into Tournaments (name, year, location, winner_id) values ('Spring Invitational', 1985, 'Brazil', 806);
insert into Tournaments (name, year, location, winner_id) values ('Masters Open', 2015, 'Sydney', 917);
insert into Tournaments (name, year, location, winner_id) values ('Winter Classic', 2003, 'Brazil', 669);
insert into Tournaments (name, year, location, winner_id) values ('Masters Open', 2006, 'Sydney', 974);
insert into Tournaments (name, year, location, winner_id) values ('Winter Classic', 2016, 'New York', 498);
insert into Tournaments (name, year, location, winner_id) values ('Grand Prix', 1983, 'Tokyo', 94);
insert into Tournaments (name, year, location, winner_id) values ('World Series', 2023, 'Brazil', 391);
insert into Tournaments (name, year, location, winner_id) values ('Grand Prix', 1983, 'New York', 938);
insert into Tournaments (name, year, location, winner_id) values ('Champions Cup', 1995, 'Australia', 643);
insert into Tournaments (name, year, location, winner_id) values ('Spring Invitational', 1984, 'Brazil', 915);
insert into Tournaments (name, year, location, winner_id) values ('Grand Prix', 1984, 'São Paulo', 792);
insert into Tournaments (name, year, location, winner_id) values ('Spring Invitational', 1981, 'Toronto', 720);
insert into Tournaments (name, year, location, winner_id) values ('Grand Prix', 2012, 'USA', 369);
insert into Tournaments (name, year, location, winner_id) values ('Champions Cup', 1990, 'Germany', 938);
insert into Tournaments (name, year, location, winner_id) values ('Spring Invitational', 1985, 'Germany', 46);
insert into Tournaments (name, year, location, winner_id) values ('Grand Prix', 1991, 'São Paulo', 505);
insert into Tournaments (name, year, location, winner_id) values ('Masters Open', 1999, 'Berlin', 741);
insert into Tournaments (name, year, location, winner_id) values ('Masters Open', 1980, 'Australia', 40);
insert into Tournaments (name, year, location, winner_id) values ('Spring Invitational', 2009, 'Berlin', 306);
insert into Tournaments (name, year, location, winner_id) values ('Continental Championship', 1998, 'Sydney', 124);
insert into Tournaments (name, year, location, winner_id) values ('Masters Open', 2025, 'Brazil', 739);
insert into Tournaments (name, year, location, winner_id) values ('Continental Championship', 2017, 'Tokyo', 876);
insert into Tournaments (name, year, location, winner_id) values ('Spring Invitational', 1984, 'UK', 250);
insert into Tournaments (name, year, location, winner_id) values ('Masters Open', 2024, 'Japan', 85);
insert into Tournaments (name, year, location, winner_id) values ('Grand Prix', 1996, 'Toronto', 2);
insert into Tournaments (name, year, location, winner_id) values ('Grand Prix', 1992, 'UK', 198);
insert into Tournaments (name, year, location, winner_id) values ('World Series', 2016, 'Berlin', 460);
insert into Tournaments (name, year, location, winner_id) values ('Masters Open', 1988, 'Sydney', 115);
insert into Tournaments (name, year, location, winner_id) values ('Grand Prix', 2016, 'Japan', 549);
insert into Tournaments (name, year, location, winner_id) values ('Winter Classic', 1980, 'Sydney', 578);
insert into Tournaments (name, year, location, winner_id) values ('Spring Invitational', 1994, 'Brazil', 871);
insert into Tournaments (name, year, location, winner_id) values ('Champions Cup', 1991, 'Canada', 39);
insert into Tournaments (name, year, location, winner_id) values ('Masters Open', 1982, 'Canada', 577);
insert into Tournaments (name, year, location, winner_id) values ('Continental Championship', 1993, 'New York', 590);
insert into Tournaments (name, year, location, winner_id) values ('Champions Cup', 1999, 'Canada', 289);
insert into Tournaments (name, year, location, winner_id) values ('Champions Cup', 2007, 'Germany', 239);
insert into Tournaments (name, year, location, winner_id) values ('Winter Classic', 1992, 'London', 145);
insert into Tournaments (name, year, location, winner_id) values ('Masters Open', 2010, 'Germany', 688);
insert into Tournaments (name, year, location, winner_id) values ('Masters Open', 2002, 'Germany', 505);
insert into Tournaments (name, year, location, winner_id) values ('Continental Championship', 1999, 'Germany', 877);
insert into Tournaments (name, year, location, winner_id) values ('Spring Invitational', 1988, 'Sydney', 174);
insert into Tournaments (name, year, location, winner_id) values ('Continental Championship', 2022, 'Berlin', 755);
insert into Tournaments (name, year, location, winner_id) values ('World Series', 2000, 'New York', 139);
insert into Tournaments (name, year, location, winner_id) values ('Masters Open', 2021, 'Canada', 596);
insert into Tournaments (name, year, location, winner_id) values ('Spring Invitational', 1992, 'UK', 214);
insert into Tournaments (name, year, location, winner_id) values ('Masters Open', 2019, 'Sydney', 273);
insert into Tournaments (name, year, location, winner_id) values ('Masters Open', 2021, 'Tokyo', 984);
insert into Tournaments (name, year, location, winner_id) values ('Champions Cup', 1993, 'Toronto', 62);
insert into Tournaments (name, year, location, winner_id) values ('Grand Prix', 2008, 'Germany', 268);
insert into Tournaments (name, year, location, winner_id) values ('World Series', 1996, 'UK', 379);
insert into Tournaments (name, year, location, winner_id) values ('Spring Invitational', 1994, 'UK', 406);
insert into Tournaments (name, year, location, winner_id) values ('Winter Classic', 1996, 'Canada', 180);
insert into Tournaments (name, year, location, winner_id) values ('Spring Invitational', 1992, 'São Paulo', 74);
insert into Tournaments (name, year, location, winner_id) values ('Champions Cup', 2002, 'Germany', 808);
insert into Tournaments (name, year, location, winner_id) values ('Grand Prix', 2015, 'New York', 958);
insert into Tournaments (name, year, location, winner_id) values ('Masters Open', 2015, 'USA', 293);
insert into Tournaments (name, year, location, winner_id) values ('Masters Open', 1998, 'Tokyo', 956);
insert into Tournaments (name, year, location, winner_id) values ('Grand Prix', 2002, 'Sydney', 35);
insert into Tournaments (name, year, location, winner_id) values ('Continental Championship', 1982, 'New York', 250);
insert into Tournaments (name, year, location, winner_id) values ('Winter Classic', 2024, 'Berlin', 30);
insert into Tournaments (name, year, location, winner_id) values ('Grand Prix', 2004, 'Canada', 457);
insert into Tournaments (name, year, location, winner_id) values ('Masters Open', 2001, 'UK', 147);
insert into Tournaments (name, year, location, winner_id) values ('Champions Cup', 2011, 'Brazil', 491);
insert into Tournaments (name, year, location, winner_id) values ('Winter Classic', 1993, 'USA', 404);
insert into Tournaments (name, year, location, winner_id) values ('World Series', 1983, 'USA', 762);
insert into Tournaments (name, year, location, winner_id) values ('Champions Cup', 2010, 'Sydney', 307);
insert into Tournaments (name, year, location, winner_id) values ('Champions Cup', 2020, 'Tokyo', 253);
insert into Tournaments (name, year, location, winner_id) values ('Grand Prix', 1986, 'Berlin', 507);
insert into Tournaments (name, year, location, winner_id) values ('Continental Championship', 2000, 'Germany', 163);
insert into Tournaments (name, year, location, winner_id) values ('Spring Invitational', 1984, 'New York', 775);
insert into Tournaments (name, year, location, winner_id) values ('Winter Classic', 1997, 'Germany', 233);
insert into Tournaments (name, year, location, winner_id) values ('Grand Prix', 1980, 'Brazil', 184);
insert into Tournaments (name, year, location, winner_id) values ('Champions Cup', 2016, 'São Paulo', 272);
insert into Tournaments (name, year, location, winner_id) values ('Grand Prix', 2013, 'New York', 87);
insert into Tournaments (name, year, location, winner_id) values ('Grand Prix', 2022, 'Australia', 543);
insert into Tournaments (name, year, location, winner_id) values ('Champions Cup', 1997, 'Toronto', 633);
insert into Tournaments (name, year, location, winner_id) values ('Spring Invitational', 2025, 'Germany', 772);
insert into Tournaments (name, year, location, winner_id) values ('Spring Invitational', 1981, 'Japan', 141);
insert into Tournaments (name, year, location, winner_id) values ('Champions Cup', 1999, 'Germany', 357);
insert into Tournaments (name, year, location, winner_id) values ('Continental Championship', 1987, 'Canada', 462);
insert into Tournaments (name, year, location, winner_id) values ('Grand Prix', 2002, 'Sydney', 509);
insert into Tournaments (name, year, location, winner_id) values ('World Series', 1982, 'Toronto', 301);
insert into Tournaments (name, year, location, winner_id) values ('Champions Cup', 1994, 'Sydney', 432);
insert into Tournaments (name, year, location, winner_id) values ('Continental Championship', 1982, 'Germany', 975);
insert into Tournaments (name, year, location, winner_id) values ('Continental Championship', 1982, 'USA', 949);
insert into Tournaments (name, year, location, winner_id) values ('Continental Championship', 2014, 'Canada', 419);
insert into Tournaments (name, year, location, winner_id) values ('Champions Cup', 2022, 'Sydney', 632);
insert into Tournaments (name, year, location, winner_id) values ('Continental Championship', 2005, 'Sydney', 351);
insert into Tournaments (name, year, location, winner_id) values ('Masters Open', 1996, 'USA', 51);
insert into Tournaments (name, year, location, winner_id) values ('Grand Prix', 2007, 'Japan', 898);
insert into Tournaments (name, year, location, winner_id) values ('Continental Championship', 2004, 'Sydney', 112);
insert into Tournaments (name, year, location, winner_id) values ('Champions Cup', 1998, 'Germany', 55);
insert into Tournaments (name, year, location, winner_id) values ('Grand Prix', 1983, 'Brazil', 578);
insert into Tournaments (name, year, location, winner_id) values ('Winter Classic', 1991, 'Germany', 669);
insert into Tournaments (name, year, location, winner_id) values ('Spring Invitational', 2021, 'USA', 992);
insert into Tournaments (name, year, location, winner_id) values ('Continental Championship', 2011, 'Canada', 768);
insert into Tournaments (name, year, location, winner_id) values ('Winter Classic', 1997, 'Tokyo', 115);
insert into Tournaments (name, year, location, winner_id) values ('Champions Cup', 2012, 'Japan', 364);
insert into Tournaments (name, year, location, winner_id) values ('Winter Classic', 1980, 'São Paulo', 57);
insert into Tournaments (name, year, location, winner_id) values ('Continental Championship', 2022, 'UK', 805);
insert into Tournaments (name, year, location, winner_id) values ('Masters Open', 2001, 'Germany', 624);
insert into Tournaments (name, year, location, winner_id) values ('Spring Invitational', 2000, 'Toronto', 890);
insert into Tournaments (name, year, location, winner_id) values ('Champions Cup', 1983, 'Brazil', 341);
insert into Tournaments (name, year, location, winner_id) values ('Spring Invitational', 2016, 'Tokyo', 748);
insert into Tournaments (name, year, location, winner_id) values ('World Series', 2001, 'Sydney', 832);
insert into Tournaments (name, year, location, winner_id) values ('Winter Classic', 2012, 'Canada', 815);
insert into Tournaments (name, year, location, winner_id) values ('Masters Open', 1987, 'Australia', 62);
insert into Tournaments (name, year, location, winner_id) values ('Champions Cup', 2003, 'Australia', 797);
insert into Tournaments (name, year, location, winner_id) values ('World Series', 2014, 'Canada', 518);
insert into Tournaments (name, year, location, winner_id) values ('World Series', 2006, 'USA', 698);
insert into Tournaments (name, year, location, winner_id) values ('Champions Cup', 1995, 'London', 323);
insert into Tournaments (name, year, location, winner_id) values ('Champions Cup', 2013, 'Japan', 220);
insert into Tournaments (name, year, location, winner_id) values ('Winter Classic', 1985, 'Berlin', 798);
insert into Tournaments (name, year, location, winner_id) values ('World Series', 2010, 'Berlin', 213);
insert into Tournaments (name, year, location, winner_id) values ('Winter Classic', 2013, 'New York', 155);
insert into Tournaments (name, year, location, winner_id) values ('Spring Invitational', 2013, 'Toronto', 790);
insert into Tournaments (name, year, location, winner_id) values ('Spring Invitational', 2012, 'Brazil', 794);
insert into Tournaments (name, year, location, winner_id) values ('Champions Cup', 2019, 'Toronto', 638);
insert into Tournaments (name, year, location, winner_id) values ('Continental Championship', 2020, 'Australia', 834);
insert into Tournaments (name, year, location, winner_id) values ('Masters Open', 2018, 'Germany', 277);
insert into Tournaments (name, year, location, winner_id) values ('Spring Invitational', 2002, 'Japan', 959);
insert into Tournaments (name, year, location, winner_id) values ('Continental Championship', 2015, 'São Paulo', 400);
insert into Tournaments (name, year, location, winner_id) values ('Champions Cup', 2008, 'Brazil', 141);
insert into Tournaments (name, year, location, winner_id) values ('Continental Championship', 2004, 'Tokyo', 602);
insert into Tournaments (name, year, location, winner_id) values ('Spring Invitational', 2004, 'Japan', 40);
insert into Tournaments (name, year, location, winner_id) values ('World Series', 2012, 'Toronto', 551);
insert into Tournaments (name, year, location, winner_id) values ('Grand Prix', 2020, 'New York', 37);
insert into Tournaments (name, year, location, winner_id) values ('Winter Classic', 2022, 'Brazil', 519);
insert into Tournaments (name, year, location, winner_id) values ('Grand Prix', 1997, 'Australia', 267);
insert into Tournaments (name, year, location, winner_id) values ('Continental Championship', 1983, 'Brazil', 616);
insert into Tournaments (name, year, location, winner_id) values ('Spring Invitational', 1989, 'London', 100);
insert into Tournaments (name, year, location, winner_id) values ('Champions Cup', 1998, 'UK', 138);
insert into Tournaments (name, year, location, winner_id) values ('Winter Classic', 1998, 'Australia', 556);
insert into Tournaments (name, year, location, winner_id) values ('Masters Open', 1994, 'Australia', 83);
insert into Tournaments (name, year, location, winner_id) values ('Champions Cup', 1994, 'Toronto', 173);
insert into Tournaments (name, year, location, winner_id) values ('World Series', 2020, 'Australia', 371);
insert into Tournaments (name, year, location, winner_id) values ('Champions Cup', 1983, 'London', 211);
insert into Tournaments (name, year, location, winner_id) values ('Continental Championship', 2013, 'Canada', 389);
insert into Tournaments (name, year, location, winner_id) values ('Winter Classic', 1999, 'Tokyo', 858);
insert into Tournaments (name, year, location, winner_id) values ('Continental Championship', 1982, 'London', 199);
insert into Tournaments (name, year, location, winner_id) values ('World Series', 1981, 'São Paulo', 859);
insert into Tournaments (name, year, location, winner_id) values ('World Series', 2002, 'Brazil', 242);
insert into Tournaments (name, year, location, winner_id) values ('Continental Championship', 2025, 'New York', 806);
insert into Tournaments (name, year, location, winner_id) values ('Continental Championship', 2016, 'Japan', 148);
insert into Tournaments (name, year, location, winner_id) values ('Champions Cup', 1993, 'Canada', 211);
insert into Tournaments (name, year, location, winner_id) values ('Spring Invitational', 1987, 'Brazil', 330);
insert into Tournaments (name, year, location, winner_id) values ('Winter Classic', 2017, 'Germany', 436);
insert into Tournaments (name, year, location, winner_id) values ('Masters Open', 2006, 'London', 162);
insert into Tournaments (name, year, location, winner_id) values ('Grand Prix', 1981, 'London', 859);
insert into Tournaments (name, year, location, winner_id) values ('Continental Championship', 2002, 'UK', 845);
insert into Tournaments (name, year, location, winner_id) values ('World Series', 2012, 'Canada', 821);
insert into Tournaments (name, year, location, winner_id) values ('Spring Invitational', 1993, 'Berlin', 616);
insert into Tournaments (name, year, location, winner_id) values ('Grand Prix', 2015, 'UK', 388);
insert into Tournaments (name, year, location, winner_id) values ('Spring Invitational', 2001, 'Japan', 684);
insert into Tournaments (name, year, location, winner_id) values ('Grand Prix', 2009, 'Berlin', 451);
insert into Tournaments (name, year, location, winner_id) values ('Masters Open', 2001, 'Tokyo', 658);
insert into Tournaments (name, year, location, winner_id) values ('Spring Invitational', 2018, 'Toronto', 180);
insert into Tournaments (name, year, location, winner_id) values ('Masters Open', 1998, 'Canada', 421);
insert into Tournaments (name, year, location, winner_id) values ('Masters Open', 1982, 'Germany', 434);
insert into Tournaments (name, year, location, winner_id) values ('World Series', 2008, 'Sydney', 406);
insert into Tournaments (name, year, location, winner_id) values ('Champions Cup', 1997, 'Japan', 45);
insert into Tournaments (name, year, location, winner_id) values ('Grand Prix', 2024, 'Tokyo', 584);
insert into Tournaments (name, year, location, winner_id) values ('Champions Cup', 1987, 'Sydney', 736);
insert into Tournaments (name, year, location, winner_id) values ('World Series', 2024, 'Berlin', 701);
insert into Tournaments (name, year, location, winner_id) values ('Winter Classic', 1994, 'São Paulo', 213);
insert into Tournaments (name, year, location, winner_id) values ('Grand Prix', 1999, 'Brazil', 366);
insert into Tournaments (name, year, location, winner_id) values ('Masters Open', 1998, 'USA', 891);
insert into Tournaments (name, year, location, winner_id) values ('Spring Invitational', 1981, 'Canada', 128);
insert into Tournaments (name, year, location, winner_id) values ('Champions Cup', 2003, 'Germany', 937);
insert into Tournaments (name, year, location, winner_id) values ('World Series', 1994, 'Tokyo', 541);
insert into Tournaments (name, year, location, winner_id) values ('World Series', 2008, 'Toronto', 381);
insert into Tournaments (name, year, location, winner_id) values ('World Series', 2006, 'Berlin', 193);
insert into Tournaments (name, year, location, winner_id) values ('Spring Invitational', 1983, 'USA', 63);
insert into Tournaments (name, year, location, winner_id) values ('Winter Classic', 1995, 'Japan', 846);
insert into Tournaments (name, year, location, winner_id) values ('Winter Classic', 1991, 'New York', 345);
insert into Tournaments (name, year, location, winner_id) values ('Continental Championship', 1992, 'Brazil', 418);
insert into Tournaments (name, year, location, winner_id) values ('Winter Classic', 2020, 'Japan', 622);
insert into Tournaments (name, year, location, winner_id) values ('Continental Championship', 1997, 'Canada', 344);
insert into Tournaments (name, year, location, winner_id) values ('Champions Cup', 1999, 'Toronto', 471);
insert into Tournaments (name, year, location, winner_id) values ('World Series', 1991, 'London', 219);
insert into Tournaments (name, year, location, winner_id) values ('Champions Cup', 2001, 'Germany', 915);
insert into Tournaments (name, year, location, winner_id) values ('Continental Championship', 1988, 'Canada', 621);
insert into Tournaments (name, year, location, winner_id) values ('Continental Championship', 2025, 'Berlin', 578);
insert into Tournaments (name, year, location, winner_id) values ('Winter Classic', 1985, 'Berlin', 966);
insert into Tournaments (name, year, location, winner_id) values ('Grand Prix', 1995, 'Germany', 91);
insert into Tournaments (name, year, location, winner_id) values ('World Series', 2000, 'Brazil', 995);
insert into Tournaments (name, year, location, winner_id) values ('Continental Championship', 2022, 'London', 775);
insert into Tournaments (name, year, location, winner_id) values ('Winter Classic', 1999, 'Toronto', 479);
insert into Tournaments (name, year, location, winner_id) values ('Winter Classic', 1989, 'Brazil', 260);
insert into Tournaments (name, year, location, winner_id) values ('Continental Championship', 2004, 'Toronto', 15);
insert into Tournaments (name, year, location, winner_id) values ('Spring Invitational', 1997, 'Tokyo', 635);
insert into Tournaments (name, year, location, winner_id) values ('World Series', 2006, 'Germany', 385);
insert into Tournaments (name, year, location, winner_id) values ('Grand Prix', 1987, 'Toronto', 845);
insert into Tournaments (name, year, location, winner_id) values ('Continental Championship', 1981, 'Toronto', 38);
insert into Tournaments (name, year, location, winner_id) values ('Winter Classic', 1998, 'Japan', 173);
insert into Tournaments (name, year, location, winner_id) values ('Grand Prix', 2007, 'Canada', 5);
insert into Tournaments (name, year, location, winner_id) values ('Winter Classic', 1992, 'Japan', 750);
insert into Tournaments (name, year, location, winner_id) values ('Spring Invitational', 1992, 'Berlin', 435);
insert into Tournaments (name, year, location, winner_id) values ('Spring Invitational', 1999, 'São Paulo', 710);
insert into Tournaments (name, year, location, winner_id) values ('Champions Cup', 2002, 'Berlin', 493);
insert into Tournaments (name, year, location, winner_id) values ('Masters Open', 1980, 'Australia', 53);
insert into Tournaments (name, year, location, winner_id) values ('Spring Invitational', 2007, 'Japan', 659);
insert into Tournaments (name, year, location, winner_id) values ('World Series', 2004, 'London', 487);
insert into Tournaments (name, year, location, winner_id) values ('World Series', 2001, 'Berlin', 834);
insert into Tournaments (name, year, location, winner_id) values ('Grand Prix', 2016, 'Tokyo', 462);
insert into Tournaments (name, year, location, winner_id) values ('Spring Invitational', 1995, 'Germany', 95);
insert into Tournaments (name, year, location, winner_id) values ('Continental Championship', 2022, 'Australia', 101);
insert into Tournaments (name, year, location, winner_id) values ('Champions Cup', 1982, 'Canada', 464);
insert into Tournaments (name, year, location, winner_id) values ('Spring Invitational', 1985, 'London', 350);
insert into Tournaments (name, year, location, winner_id) values ('World Series', 2017, 'USA', 759);
insert into Tournaments (name, year, location, winner_id) values ('Champions Cup', 2007, 'Sydney', 866);
insert into Tournaments (name, year, location, winner_id) values ('Spring Invitational', 1991, 'São Paulo', 409);
insert into Tournaments (name, year, location, winner_id) values ('Continental Championship', 1981, 'Brazil', 74);
insert into Tournaments (name, year, location, winner_id) values ('Continental Championship', 2006, 'New York', 762);
insert into Tournaments (name, year, location, winner_id) values ('Continental Championship', 2013, 'Toronto', 319);
insert into Tournaments (name, year, location, winner_id) values ('World Series', 2009, 'Sydney', 499);
insert into Tournaments (name, year, location, winner_id) values ('Continental Championship', 2012, 'Japan', 385);
insert into Tournaments (name, year, location, winner_id) values ('Champions Cup', 1992, 'Sydney', 241);
insert into Tournaments (name, year, location, winner_id) values ('Grand Prix', 1986, 'Sydney', 396);
insert into Tournaments (name, year, location, winner_id) values ('Winter Classic', 1983, 'Australia', 907);
insert into Tournaments (name, year, location, winner_id) values ('Grand Prix', 1991, 'Japan', 990);
insert into Tournaments (name, year, location, winner_id) values ('Grand Prix', 1990, 'Tokyo', 733);
insert into Tournaments (name, year, location, winner_id) values ('Champions Cup', 1995, 'UK', 279);
insert into Tournaments (name, year, location, winner_id) values ('Grand Prix', 2011, 'Canada', 562);
insert into Tournaments (name, year, location, winner_id) values ('Continental Championship', 2023, 'Tokyo', 200);
insert into Tournaments (name, year, location, winner_id) values ('Masters Open', 1992, 'Berlin', 159);
insert into Tournaments (name, year, location, winner_id) values ('Masters Open', 1987, 'Canada', 934);
insert into Tournaments (name, year, location, winner_id) values ('Winter Classic', 1994, 'Germany', 261);
insert into Tournaments (name, year, location, winner_id) values ('Winter Classic', 1984, 'Berlin', 604);
insert into Tournaments (name, year, location, winner_id) values ('Champions Cup', 1991, 'New York', 147);
insert into Tournaments (name, year, location, winner_id) values ('Grand Prix', 2021, 'UK', 158);
insert into Tournaments (name, year, location, winner_id) values ('Continental Championship', 1999, 'Berlin', 401);
insert into Tournaments (name, year, location, winner_id) values ('Spring Invitational', 2000, 'London', 731);
insert into Tournaments (name, year, location, winner_id) values ('Grand Prix', 2009, 'London', 985);
insert into Tournaments (name, year, location, winner_id) values ('Grand Prix', 1985, 'São Paulo', 280);
insert into Tournaments (name, year, location, winner_id) values ('Spring Invitational', 1999, 'Toronto', 496);
insert into Tournaments (name, year, location, winner_id) values ('Spring Invitational', 2021, 'Japan', 860);
insert into Tournaments (name, year, location, winner_id) values ('World Series', 1999, 'Germany', 440);
insert into Tournaments (name, year, location, winner_id) values ('Spring Invitational', 2025, 'Brazil', 548);
insert into Tournaments (name, year, location, winner_id) values ('Masters Open', 1989, 'Brazil', 881);
insert into Tournaments (name, year, location, winner_id) values ('Continental Championship', 1997, 'São Paulo', 467);
insert into Tournaments (name, year, location, winner_id) values ('Continental Championship', 2012, 'Australia', 42);
insert into Tournaments (name, year, location, winner_id) values ('Champions Cup', 2009, 'Germany', 195);
insert into Tournaments (name, year, location, winner_id) values ('Winter Classic', 2009, 'Toronto', 820);
insert into Tournaments (name, year, location, winner_id) values ('Grand Prix', 2020, 'Germany', 195);
insert into Tournaments (name, year, location, winner_id) values ('World Series', 2005, 'Australia', 902);
insert into Tournaments (name, year, location, winner_id) values ('Continental Championship', 2014, 'New York', 267);
insert into Tournaments (name, year, location, winner_id) values ('Champions Cup', 2010, 'Tokyo', 206);
insert into Tournaments (name, year, location, winner_id) values ('Winter Classic', 1982, 'Berlin', 921);
insert into Tournaments (name, year, location, winner_id) values ('Masters Open', 2011, 'Canada', 208);
insert into Tournaments (name, year, location, winner_id) values ('Champions Cup', 1981, 'Brazil', 939);
insert into Tournaments (name, year, location, winner_id) values ('Continental Championship', 2025, 'Tokyo', 64);
insert into Tournaments (name, year, location, winner_id) values ('Spring Invitational', 2004, 'Toronto', 965);
insert into Tournaments (name, year, location, winner_id) values ('Masters Open', 2024, 'Germany', 621);
insert into Tournaments (name, year, location, winner_id) values ('Champions Cup', 1997, 'USA', 587);
insert into Tournaments (name, year, location, winner_id) values ('Winter Classic', 1985, 'Brazil', 22);
insert into Tournaments (name, year, location, winner_id) values ('Spring Invitational', 1991, 'USA', 318);
insert into Tournaments (name, year, location, winner_id) values ('Spring Invitational', 2024, 'Brazil', 501);
insert into Tournaments (name, year, location, winner_id) values ('Continental Championship', 1986, 'Germany', 622);
insert into Tournaments (name, year, location, winner_id) values ('Masters Open', 2005, 'Germany', 138);
insert into Tournaments (name, year, location, winner_id) values ('World Series', 2012, 'Germany', 317);
insert into Tournaments (name, year, location, winner_id) values ('Continental Championship', 2000, 'Berlin', 471);
insert into Tournaments (name, year, location, winner_id) values ('Champions Cup', 2015, 'Australia', 43);
insert into Tournaments (name, year, location, winner_id) values ('Spring Invitational', 1981, 'Germany', 987);
insert into Tournaments (name, year, location, winner_id) values ('World Series', 2011, 'Toronto', 202);
insert into Tournaments (name, year, location, winner_id) values ('Masters Open', 1981, 'Sydney', 870);
insert into Tournaments (name, year, location, winner_id) values ('World Series', 2001, 'Japan', 181);
insert into Tournaments (name, year, location, winner_id) values ('Continental Championship', 2021, 'Tokyo', 992);
insert into Tournaments (name, year, location, winner_id) values ('Spring Invitational', 2013, 'Japan', 473);
insert into Tournaments (name, year, location, winner_id) values ('World Series', 2007, 'Brazil', 88);
insert into Tournaments (name, year, location, winner_id) values ('Champions Cup', 1999, 'Brazil', 184);
insert into Tournaments (name, year, location, winner_id) values ('Champions Cup', 1981, 'Tokyo', 576);
insert into Tournaments (name, year, location, winner_id) values ('Champions Cup', 1992, 'New York', 978);
insert into Tournaments (name, year, location, winner_id) values ('Champions Cup', 1991, 'Germany', 882);
insert into Tournaments (name, year, location, winner_id) values ('World Series', 2015, 'Tokyo', 113);
